### ISSUE TITLE
Context history isn't posted at once but is instead "chunked".

### ISSUE THREAD

**Issue by manwith33** [GlizzyChief/SillyTavern-1.8.4-fix#12]
Is there a way to have unlimited context without Chunked Generation? Or at least a higher context than 4096 tokens?  Poe doesn't appear to have a limit to the amount of text that can be posted at once into Claude 2 100k, yet this version of Sillytavern insists on automatically chunking the post to Poe when I go above 4096 tokens.   It seems to do chunks whether or not I have "unlocked context selected."  I have an author's note that is very long and serves as a jailbreak that pushes it above 4096 pretty quickly.

**Comment by GlizzyChief** [comment]
@manwith33 I know this is very late, and I'm sorry for that, but did you find a way to do that? For now, it can be changed in the source code, but if you want to I can add it to connection settings!

**Comment by manwith33** [comment]
@GlizzyChief  If you could change it that would be great. I'm not a programmer and only closed the issue because I wasn't sure whether to request it here or at the 1.9.7 fork of your project https://github.com/LegendPoet/SillyTavern-fix.

I have both installed on my PC and if you made the change I'd use your version. Thanks.

**Comment by GlizzyChief** [comment]
@manwith33 Sure! It will take me some time to implement the UI part of it though, as I don't have much time currently. For now, please do the following to change it to your heart's content.
1. Navigate to the public/scripts folder
2. Open "poe.js" in Notepad (or any other text editor of your choice
3. Go to the 30th line (const POE_TOKEN_LENGTH = 2048;) and change 2048 to anything you want. Since you want unlimited token window before chunking, I suggest just assigning an absurd number to it, like 100000.
4. Save and enjoy!

Please contact me via Discord and I'll gladly help you, I'm usually active there, and not as much here due to having to login every time I want to do anything here). By the way, this method works for both 1.9.7 and this version, don't hesitate to reach out about any issues related to the fork, I'll do what I can with them, and once I get to implement the UI part, I'll submit a pull request there as well. I hope this helps, and once again, please contact me via Discord for any help you might need!

**Comment by manwith33** [comment]
Thank you for your help with this. I just wanted to let you know your solution worked great, and I just figured out a

**Comment by GlizzyChief** [comment]
OH damn, I completely ignored the AND clause, banging my head on why it wasn't working, and I even added a fancy way to customize the batch length. Thanks! I looked over the code like 3 times and ignored && every time! An update will be out in about 1 minute from now

**Comment by GlizzyChief** [comment]
Forgot to update the case. Update is long out, please update and it should work properly!  Closing the case, please contact me if any issues arise.
